trigger:
- none

stages:

- stage: 'ProdEnvironmentNetworking'
  dependsOn: []
  displayName: Prod Environment Networking

  jobs:
    - job: 'TerraformInitPlan_Networking'
      displayName: 'Initialize and Plan Terraform for Prod Environment Networking'
      pool: Self-Hosted
      
      steps:
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            backendType: 'azurerm'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.networking.terraform.tfstate'
            allowTelemetryCollection: false

        - task: TerraformCLI@0
          inputs:
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg/'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/vnet_subnet_nsg/prod.tfvars'
            environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
            allowTelemetryCollection: false
            
- stage: 'ProdEnvironmentNetworkingApply'
  dependsOn: []
  displayName: Prod Environment Networking Apply
  
  jobs:          
    - deployment: 'TerraformApply_Networking'
      displayName: 'Apply Terraform for Prod Environment Networking'
      pool: Self-Hosted
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - task: TerraformCLI@0
                inputs:
                  command: 'apply'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg/'
                  commandOptions: '-var-file="/terraform/variables/terraform-azure/vnet_subnet_nsg/prod.tfvars'
                  environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
                  allowTelemetryCollection: false
            
- stage: 'ProdEnvironmentKeyVault'
  dependsOn: []
  displayName: Prod Environment Key Vault
  
  jobs:          
    - job: 'TerraformInitPlan_KeyVault'
      displayName: 'Initialize and Plan Terraform for Dev Environment Key Vault'
      pool: Self-Hosted
      
      steps:
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            backendType: 'azurerm'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.keyvault.terraform.tfstate'
            allowTelemetryCollection: false

        - task: TerraformCLI@0
          inputs:
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault/'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/key_vault/prod.tfvars'
            environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
            allowTelemetryCollection: false
            
- stage: 'ProdEnvironmentKeyVaultApply'
  dependsOn: []
  displayName: Prod Environment Key Vault Apply
  
  jobs:          
    - deployment: 'TerraformApply_KeyVault'
      displayName: 'Apply Terraform for Prod Environment Key Vault'
      pool: Self-Hosted
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - task: TerraformCLI@0
                inputs:
                  command: 'apply'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault/'
                  commandOptions: '-var-file="/terraform/variables/terraform-azure/key_vault/prod.tfvars'
                  environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
                  allowTelemetryCollection: false
            
- stage: 'ProdEnvironmentLinuxVM'
  dependsOn: []
  displayName: Prod Environment Linux VM

  jobs:          
    - job: 'TerraformInitPlan_LinuxVM'
      displayName: 'Initialize and Plan Terraform for Prod Environment Linux VM'
      pool: Self-Hosted
      steps:
        - task: TerraformCLI@0
          inputs:
            backendType: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux/'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.virtualmachines.terraform.tfstate'
            allowTelemetryCollection: false

        - task: TerraformCLI@0
          inputs:
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux/'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/prod.tfvars'
            environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
            allowTelemetryCollection: false
            
- stage: 'ProdEnvironmentLinuxVMApply'
  dependsOn: []
  displayName: Prod Environment Linux VM Apply
  
  jobs:          
    - deployment: 'TerraformApply_LinuxVM'
      displayName: 'Apply Terraform for Prod Environment Linux VM'
      pool: Self-Hosted
      environment: Prod
      strategy:
        runOnce:
          deploy:     
            steps:
              - task: TerraformCLI@0
                inputs:
                  command: 'apply'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux/'
                  commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/prod.tfvars'
                  environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
                  allowTelemetryCollection: false

- stage: 'ProdEnvironmentWindowsVM'
  dependsOn: []
  displayName: Prod Environment Windows VM

  jobs:
    - job: 'TerraformInitPlan_WindowsVM'
      displayName: 'Initialize and Plan Terraform for Prod Environment Windows VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformCLI@0
          inputs:
            backendType: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/windows/'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.virtualmachines.terraform.tfstate'
            allowTelemetryCollection: false

        - task: TerraformCLI@0
          inputs:
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/windows/'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/windows/prod.tfvars'
            environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
            allowTelemetryCollection: false

- stage: 'ProdEnvironmentWindowsVMApply'
  dependsOn: []
  displayName: Prod Environment Windows VM Apply
  
  jobs:          
    - deployment: 'TerraformApply_WindowsVM'
      displayName: 'Apply Terraform for Prod Environment Windows VM'
      pool: Self-Hosted
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - task: TerraformCLI@0
                inputs:
                  command: 'apply'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/windows/'
                  commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/windows/prod.tfvars'
                  environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
                  allowTelemetryCollection: false
      
