trigger:
- none

stages:

- stage: 'ProdEnvironmentNetworking'
  dependsOn: []
  displayName: Prod Environment Networking

  jobs:
    - job: 'TerraformInit_Networking'
      displayName: 'Initialize Terraform for Prod Environment Networking'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.networking.terraform.tfstate'

    - job: 'TerraformPlan_Networking'
      dependsOn: 'TerraformInit_Networking'
      displayName: 'Run Terraform Plan for Prod Environment Networking'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/vnet_subnet_nsg/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'ProdEnvironmentNetworkingApply'
  dependsOn: []
  displayName: Prod Environment Networking Apply
  
  jobs:          
    - job: 'TerraformApply_Networking'
      displayName: 'Apply Terraform for Prod Environment Networking'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/vnet_subnet_nsg/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'ProdEnvironmentKeyVault'
  dependsOn: []
  displayName: Prod Environment Key Vault
  
  jobs:          
    - job: 'TerraformInit_KeyVault'
      displayName: 'Initialize Terraform for Prod Environment Key Vault'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.keyvault.terraform.tfstate'

    - job: 'TerraformPlan_KeyVault'
      dependsOn: 'TerraformInit_KeyVault'
      displayName: 'Run Terraform Plan for Prod Environment Key Vault'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/key_vault/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'ProdEnvironmentKeyVaultApply'
  dependsOn: []
  displayName: Prod Environment Key Vault Apply
  
  jobs:          
    - job: 'TerraformApply_KeyVault'
      displayName: 'Apply Terraform for Prod Environment Key Vault'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/key_vault/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'ProdEnvironmentLinuxVM'
  dependsOn: []
  displayName: Prod Environment Linux VM

  jobs:          
    - job: 'TerraformInit_LinuxVM'
      displayName: 'Initialize Terraform for Prod Environment Linux VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.virtualmachines.terraform.tfstate'

    - job: 'TerraformPlan_LinuxVM'
      dependsOn: 'TerraformInit_LinuxVM'
      displayName: 'Run Terraform Plan for Prod Environment Linux VM'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'ProdEnvironmentLinuxVMApply'
  dependsOn: []
  displayName: Prod Environment Linux VM Apply
  
  jobs:          
    - job: 'TerraformApply_LinuxVM'
      displayName: 'Apply Terraform for Prod Environment Linux VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'

- stage: 'ProdEnvironmentWindowsVM'
  dependsOn: []
  displayName: Prod Environment Windows VM

  jobs:
    - job: 'TerraformInit_WindowsVM'
      displayName: 'Initialize Terraform for Prod Environment Windows VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/windows'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'prod-tfstate'
            backendAzureRmKey: 'prod.virtualmachines.terraform.tfstate'

    - job: 'TerraformPlan_WindowsVM'
      dependsOn: 'TerraformInit_WindowsVM'
      displayName: 'Run Terraform Plan for Prod Environment Windows VM'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/windows'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/windows/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'

- stage: 'ProdEnvironmentWindowsVMApply'
  dependsOn: []
  displayName: Prod Environment Windows VM Apply
  
  jobs:          
    - job: 'TerraformApply_WindowsVM'
      displayName: 'Apply Terraform for Prod Environment Linux VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/prod.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
      
