trigger:
- none

stages:

- stage: 'DevEnvironmentNetworking'
  dependsOn: []
  displayName: Dev Environment Networking

  jobs:
    - job: 'TerraformInit_Networking'
      displayName: 'Initialize Terraform for Dev Environment Networking'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'dev-tfstate'
            backendAzureRmKey: 'dev.networking.terraform.tfstate'

    - job: 'TerraformPlan_Networking'
      dependsOn: 'TerraformInit_Networking'
      displayName: 'Run Terraform Plan for Dev Environment Networking'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/vnet_subnet_nsg/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'DevEnvironmentNetworkingApply'
  dependsOn: []
  displayName: Dev Environment Networking Apply
  
  jobs:          
    - job: 'TerraformApply_Networking'
      displayName: 'Apply Terraform for Dev Environment Networking'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/01_vnet_subnet_nsg'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/vnet_subnet_nsg/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'DevEnvironmentKeyVault'
  dependsOn: []
  displayName: Dev Environment Key Vault
  
  jobs:          
    - job: 'TerraformInit_KeyVault'
      displayName: 'Initialize Terraform for Dev Environment Key Vault'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'dev-tfstate'
            backendAzureRmKey: 'dev.keyvault.terraform.tfstate'

    - job: 'TerraformPlan_KeyVault'
      dependsOn: 'TerraformInit_KeyVault'
      displayName: 'Run Terraform Plan for Dev Environment Key Vault'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/key_vault/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'DevEnvironmentKeyVaultApply'
  dependsOn: []
  displayName: Dev Environment Key Vault Apply
  
  jobs:          
    - job: 'TerraformApply_KeyVault'
      displayName: 'Apply Terraform for Dev Environment Key Vault'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/02_key_vault'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/key_vault/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'DevEnvironmentLinuxVM'
  dependsOn: []
  displayName: Dev Environment Linux VM

  jobs:          
    - job: 'TerraformInit_LinuxVM'
      displayName: 'Initialize Terraform for Dev Environment Linux VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'dev-tfstate'
            backendAzureRmKey: 'dev.virtualmachines.terraform.tfstate'

    - job: 'TerraformPlan_LinuxVM'
      dependsOn: 'TerraformInit_LinuxVM'
      displayName: 'Run Terraform Plan for Dev Environment Linux VM'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
            
- stage: 'DevEnvironmentLinuxVMApply'
  dependsOn: []
  displayName: Dev Environment Linux VM Apply
  
  jobs:          
    - job: 'TerraformApply_LinuxVM'
      displayName: 'Apply Terraform for Dev Environment Linux VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'

- stage: 'DevEnvironmentWindowsVM'
  dependsOn: []
  displayName: Dev Environment Windows VM

  job:
    - job: 'TerraformInit_WindowsVM'
      displayName: 'Initialize Terraform for Dev Environment Windows VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/windows'
            backendServiceArm: 'Visual Studio Enterprise Subscription - MPN'
            backendAzureRmResourceGroupName: 'rg-storage-prod-san-01'
            backendAzureRmStorageAccountName: 'stprodtfsan01'
            backendAzureRmContainerName: 'dev-tfstate'
            backendAzureRmKey: 'dev.virtualmachines.terraform.tfstate'

    - job: 'TerraformPlan_WindowsVM'
      dependsOn: 'TerraformInit_WindowsVM'
      displayName: 'Run Terraform Plan for Dev Environment Windows VM'
      pool: Self-Hosted

      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/windows'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/windows/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'

- stage: 'DevEnvironmentWindowsVMApply'
  dependsOn: []
  displayName: Dev Environment Windows VM Apply
  
  jobs:          
    - job: 'TerraformApply_WindowsVM'
      displayName: 'Apply Terraform for Dev Environment Linux VM'
      pool: Self-Hosted
      
      steps:
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/virtual_machine/linux'
            commandOptions: '-var-file="/terraform/variables/terraform-azure/virtual_machine/linux/dev.tfvars'
            environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription - MPN'
      
