variables:
- group: terraform-azure

resources:
  repositories:
    - repository: 'TerraformVars'
      type: github
      endpoint: qman-being
      name: qman-being/terraform-vars

parameters:
  - name: terraformVersion
    type: string
    default: 'latest'

trigger:
- none

stages:

- stage: 'DevEnvironmentACI'
  dependsOn: []
  displayName: Dev Environment ACI

  jobs:          
    - job: 'TerraformInitPlan_ACI'
      displayName: 'Initialize and Plan Terraform Destroy for Dev Environment ACI'
      pool: 'Azure Pipelines'
      steps:
        - checkout: self
        - checkout: TerraformVars

        - task: TerraformInstaller@0
          displayName: 'Terraform Install'
          inputs:
            terraformVersion: ${{ parameters.terraformVersion }}

        - task: TerraformCLI@0
          displayName: 'Dev ACI Terraform Init'
          inputs:
            backendType: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azure/azure_container_instance/Dev/'
            backendServiceArm: '$(backendServiceArm)'
            backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
            backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
            backendAzureRmContainerName: 'dev-tfstate'
            backendAzureRmKey: 'dev.aci.terraform.tfstate'
            allowTelemetryCollection: false

        - task: TerraformCLI@0
          displayName: 'Dev ACI Terraform Plan Destroy'
          inputs:
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azure/azure_container_instance/Dev/'
            commandOptions: '-destroy -var-file="$(System.DefaultWorkingDirectory)/terraform-vars/variables/terraform-azure/azure_container_instance/dev.tfvars" -out ${BUILD_BUILDNUMBER}.tfplan'
            environmentServiceName: '$(backendServiceArm)'
            allowTelemetryCollection: false

        - task: ArchiveFiles@2
          condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
          displayName: 'Create Plan Artifact'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/terraform-azure/azure_container_instance/Dev/'
            includeRootFolder: false
            archiveType: 'tar'
            tarCompression: 'gz'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).tgz'
            replaceExistingArchive: true
            
        - task: PublishPipelineArtifact@1
          condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
          displayName: 'Publish Plan Artifact'
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'dev-aci-plan-destroy'
            
- stage: 'DevEnvironmentACIApply'
  dependsOn: 'DevEnvironmentACI'
  displayName: Dev Environment ACI Apply Destroy
  
  jobs:          
    - deployment: 'TerraformApply_ACI'
      displayName: 'Apply Terraform Destroy for Dev Environment ACI'
      pool: 'Azure Pipelines'
      environment: Dev
      strategy:
        runOnce:
          deploy:     
            steps:
              - checkout: self
              - checkout: TerraformVars

              - task: TerraformInstaller@0
                displayName: 'Terraform Install'
                inputs:
                  terraformVersion: ${{ parameters.terraformVersion }}

              - task: ExtractFiles@1
                displayName: 'Extract Plan Artifact'
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)/dev-aci-plan-destroy/$(Build.BuildNumber).tgz'
                  destinationFolder: '$(System.DefaultWorkingDirectory)/terraform-azure/azure_container_instance/Dev/'
                  cleanDestinationFolder: true

              - task: TerraformCLI@0
                inputs:
                  command: 'apply'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azure/azure_container_instance/Dev/'
                  commandOptions: '${BUILD_BUILDNUMBER}.tfplan'
                  environmentServiceName: 'Visual Studio Enterprise Subscription - MPN'
                  allowTelemetryCollection: false